version: 2.1

jobs:
  ecr-login:
    docker:
      - image: cimg/aws:2025.01 # CircleCI base image for AWS CLI
    steps:
      - run:
          name: Authenticate with ECR
          command: |
            aws --version
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-west-2
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 516117289716.dkr.ecr.us-west-2.amazonaws.com

  test-mvretail-environment:
    docker:
      - image: 516117289716.dkr.ecr.us-west-2.amazonaws.com/aio-automation:latest
    # environment:
    #   JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    #   PATH: /usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
    steps:
      - checkout
      - run:
         name: Verify mvretail Environment
         command: |
            echo "Testing mvretail environment..."
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            echo "Java Home: $JAVA_HOME"
            echo "Path: $PATH"
            java -version
            python --version
            php -v
            redis-server --version
            echo "Environment verified successfully!"
      - run:
          name: installing the automation requirements
          command: |
            export auto_dir=`pwd`
            mkdir logs
            env > env.txt
            export logs_dir=${auto_dir}/logs
            echo "Test run could not start!" > results.txt 
            pip3 install pip --upgrade > ${logs_dir}/python_pip_upgrade.txt 2>&1
            pip3 install --user -r requirements.txt > ${logs_dir}/python_pip_requirements_install.txt 2>&1
            echo "automation requirements finished installing"  
      - run:
          name: Branch Check and System Version Verification
          command: |
            if echo "$MVRETAIL_BRANCH" | grep -q "excludeci"; then
                echo "Branch contains excludeci keyword. No Automation Test runs against this branch!!"
                exit 0
            else
                echo "Proceed with running Automation Test runs against this branch!!"
            fi
            
            readlink /proc/$$/exe
            echo "Java Path: `which java`"
            echo "PHP Version: `php --version`"
            echo "Chromedriver Version: `chromedriver --version`"
            echo "Google Chrome Version: `google-chrome --version`"
      - run:
          name: Update /etc/hosts
          command: |
            echo "127.0.0.1 macdev2.mvretail.com" | sudo tee -a /etc/hosts
      - run:
          name: AMP Build Step (Conditional)
          command: |
            export RUN_AMP=false
            if [ "$RUN_AMP" = "true" ]; then
              echo "Starting AMP Build Process..."
              export GRADLE_OPT="-Xmx6G"

              # Clone the MVNEXT repository
              git clone --depth 1 git@github.com:MoVista/MVNEXT.git --branch $MVNEXT_BRANCH --single-branch

              export SENTRY_DISABLE_AUTO_UPLOAD=true
              echo "Starting APK build!!"

              # Fix permissions for Android SDK
              sudo chown -R root:jenkins /opt/android
              sudo chmod -R 775 /opt/android

              # Set Gradle Properties
              export ORG_GRADLE_PROJECT_RELEASE_STORE_KEY_ALIAS=MVAndroidKey
              export ORG_GRADLE_PROJECT_RELEASE_STORE_FILE=MVNEXT_Release
              export ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD=$MVNEXT_RELEASE_KEY
              export ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD=$MVNEXT_RELEASE_KEY
              export ORG_GRADLE_PROJECT_BACKGROUND_GEOLOCATION_LIB_KEY=$MVNEXT_GEO_LOCATION_KEY

              # Modify Gradle Properties File
              python3 scripts/replace_line.py MVNEXT/android/gradle.properties \
                "org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" \
                "org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

              # Build the app
              cd MVNEXT
              sudo npm install --global yarn > ${logs_dir}/yarn_global_module_install.txt 2>&1
              yarn install > ${logs_dir}/yarn_install_output.txt 2>&1
              yarn react-native bundle --platform android --dev false --entry-file index.js \
                --bundle-output android/app/src/main/assets/index.android.bundle \
                --assets-dest android/app/build/intermediates/res/merged/release/ > ${logs_dir}/yarn_asset_bundle.txt 2>&1

              cd android
              ./gradlew assembleRelease > ${logs_dir}/gradle_assemble_release.txt 2>&1

              echo "App build completed!!"
              cd $auto_dir
              cp MVNEXT/android/app/build/outputs/apk/amp/release/app-amp-release.apk .
              export apk_path=${auto_dir}/app-amp-release.apk
              sudo chmod 444 $apk_path

              echo "Cloning mvretail and simplesamlphp..."
              git clone --depth 1 git@github.com:MoVista/MVRetail.git --branch $MVRETAIL_BRANCH --single-branch > ${logs_dir}/git_mvretail_log.txt 2>&1
              git clone --depth 1 git@github.com:MoVista/SimpleSAMLphp.git --branch master --single-branch > ${logs_dir}/git_simplesamlphp_log.txt 2>&1
              mv SimpleSAMLphp simplesamlphp

              sudo cp -r MVRetail /var/www/
              sudo cp -r simplesamlphp /var/

            else
              echo "Skipping AMP build, RUN_AMP is not set to true."
            fi
workflows:
  version: 2
  deploy-and-test:
    jobs:
      - ecr-login:
          context:
            - aws-credentials
      - test-mvretail-environment:
          context:
            - aws-credentials
          requires:
            - ecr-login
